### PR TITLE
load optimizations

### PR DESCRIPTION
**Pull request by lzimm**
attempts to optimize the load and redraw path to be slightly less "pessimistic" and make faster the parts of the toolbox plugin that we actually can.

note: on my machine any sort of subprocess stuff completely blocks the renderer thread (even though it shouldn't...) and my operator still hangs when i run this, the same way running anything on third eye completely punishes my machine too, but that seems to be relatively uncommon.

@stephanwampouille wanna give this a shot?

re: https://github.com/preludeorg/operator/issues/2232

ps: i just realized that this puts the starter kit back in even though i was running off a fresh plugin i had just installed locally. nixing it back out.

### CODE REVIEW

**Comment by stephanwampouille** [comment]
so yes, it is a bit quicker but still is very slow and choppy if you try to scroll while it loads.

**Comment by lzimm** [comment]
what about now @stephanwampouille ?

@privateducky i think this might be as good as we can do, the main issue is really that the entire point of this plugin is to keep things automatically up to date for you, and even if we don't do a full pull when helping you do that, showing the last updated timestamp (which requires that pull anyways) is kind of one of tablestakes to making this a useful plugin at all (without which we're kind of not really providing enough value for this to really be worth maintaining as a plugin).

@stephanwampouille how does file hunter run on your computer w/ thirdeye?

**Comment by privateducky** [comment]
> what about now @stephanwampouille ?
> 
> @privateducky i think this might be as good as we can do, the main issue is really that the entire point of this plugin is to keep things automatically up to date for you, and even if we don't do a full pull when helping you do that, showing the last updated timestamp (which requires that pull anyways) is kind of one of tablestakes to making this a useful plugin at all (without which we're kind of not really providing enough value for this to really be worth maintaining as a plugin).
> 
> @stephanwampouille how does file hunter run on your computer w/ thirdeye?

Here's a couple of options that come to mind:
1. only pull latest code if you enter the plugin - not when Operator itself starts on top of when you enter the plugin.
2. avoid pulling the code automatically and pull it on request (a button)

One seems like the best/easiest route. Thoughts?

General notes: the biggest value of this plugin in the co-location of all your "tools", with secondary benefits being easy access to the README and commit logs of each repo. It's sort of like our mini-package manager. I'd say the tertiary benefit is the always updating function. The biggest benefit to this plugin overtime will be the tie in with other parts of Operator (like fact parsing) but we haven't had time to circle on that one.

**Comment by lzimm** [comment]
@privateducky

- we only DO pull the code when you enter the plugin as it is though.
- if we do #2 we can't show you when the repo was last updated (which, again, is kind of the bare minimum we kinda need in order to really have much of a value proposition, when it comes to "helping you keep your repos up to date") and kinda pushes the entire plugin into territory of "why does this exist, outside of creating surface area for us to maintain for no real reason" — to which i'd say it's better for the plugin to be SLOW than for us to lose the ability to show you the most recent update timestamp (which just happens to require you to pull code altogether anyways)

**Comment by privateducky** [comment]
> @privateducky
> 
>     * we only DO pull the code when you enter the plugin as it is though.
> 
>     * if we do [adding missing program #2](https://github.com/preludeorg/community/pull/2) we can't show you when the repo was last updated (which, again, is kind of the bare minimum we kinda need in order to really have much of a value proposition, when it comes to "helping you keep your repos up to date") and kinda pushes the entire plugin into territory of "why does this exist, outside of creating surface area for us to maintain for no real reason" — to which i'd say it's better for the plugin to be SLOW than for us to lose the ability to show you the most recent update timestamp (which just happens to require you to pull code altogether anyways)

I think this is one of those where everyone may find value in different places. I personally find value in having all my tools co-located and being able to pop up readme's/commit histories, etc. 

but let's break it down: 
- click a button to update/pull the latest code
- automatically pull the latest code when you enter the plugin

> @stephanwampouille did you mention Operator being slow when you start it too, or am i dreaming that?

the only difference here is, do we require the user to click a button to pull all their repos? if pulling repos is slow, i'd say yeah, that's probably something we let them decide when to do. because otherwise, i may pop in and out of the plugin to sporadically to pull up a README or see if i have a tool and have to wait 10-20s each time. putting the button there lets the user decide what they're there for: reading stuff or updating their code. in either case, we can show the last updated time. it'll just be out of date unless they click update (which seems commonsense, as it's the same as running 'git log' locally without pulling latest code).

**Comment by privateducky** [comment]
@lzimm if we were genius' we'd figure out how to "detach" thirdeye to not slow things down and pipe these git pulls to it as TTPs... 

although, you may be the only one i've seen experience the thirdeye slowness, so it may not be a bad approach...?

**Comment by lzimm** [comment]
haha, unfortunately @stephanwampouille experiences the same thirdeye thing that i do, which i think is the real issue. i'm gonna try to fix THAT instead as that actually seems like a far more serious issue. the app feels completely broken the way it is because of it, and it definitely seems not right.

**Comment by lzimm** [comment]
wanna try in combo with this guy @stephanwampouille @privateducky? https://github.com/preludeorg/operator/pull/2238

should speed up thirdeye too. still not great, but its definitely better than it was before for me at least.

**Comment by stephanwampouille** [comment]
Just tested the load times with both #207 here and https://github.com/preludeorg/operator/pull/2238. Toolbox was definitely faster than before but the problem is what David has mentioned before, that every action that initiates change in Toolbox requires Toolbox to do a refresh on 'Last Updated' and that's what takes so long.

**Comment by lzimm** [comment]
yeah i can still look at that @stephanwampouille , how does thirdeye run on master vs: with https://github.com/preludeorg/operator/pull/2238 though? what i saw on your screenshare was basically the same as what i see, which is it basically freezes the whole app for about a second every time you run ANY ttp at all, which is pretty crazy. i still get some lag with what i did in the PR, but it's way less than before for me at least.

**Comment by stephanwampouille** [comment]
@lzimm thirdly runs much faster!

**Comment by lzimm** [comment]
wooooo :) party!

**Comment by privateducky** [comment]
that PR is now merged.

back to toolbox ;) how's that impacted/look after this?

**Review by privateducky — APPROVED** [review]

**Pull request merged**
