### PR TITLE
Small Fixes in TTP files

### PR DESCRIPTION
**Pull request by w0rk3r**

### CODE REVIEW

**Comment by khyberspache** [comment]
I'm going to combine these fixes with another item I'm taking care of

**Comment by w0rk3r** [comment]
👀

**Comment by khyberspache** [comment]
Closing as we made major changes ;)

**Comment by w0rk3r** [comment]
🤔 The 'errors' persists in the newer structure

**Comment by khyberspache** [comment]
I have it covered :)

**Comment by w0rk3r** [comment]
Nice, I was going to ask if I need to open another PR but you're ahead, thanks man!

**Pull request closed without merging**
